#ifndef IR_SAMSUNG_H_INCLUDED
#define IR_SAMSUNG_H_INCLUDED

#define SAMSUNG_N_BITS 32

#define SAMSUNG_START_MIN 400 //(450-50)
#define SAMSUNG_START_MAX 500 //(450+50)

#define SAMSUNG_0_HIGH_MIN 45
#define SAMSUNG_0_HIGH_MAX 68
#define SAMSUNG_0_LOW_MIN SAMSUNG_0_HIGH_MIN
#define SAMSUNG_0_LOW_MAX SAMSUNG_0_HIGH_MAX

#define SAMSUNG_1_HIGH_MIN 45
#define SAMSUNG_1_HIGH_MAX 68
#define SAMSUNG_1_LOW_MIN 150
#define SAMSUNG_1_LOW_MAX 180

#define SAMSUNG_STOP_BIT false

#define SAMSUNG_KEY_1 0xFB040707


#endif /* IR_SAMSUNG_H_INCLUDED */
